froschwanderung_analytics:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1
      extensions:
        - parquet

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4
      extensions:
        - parquet

  target: dev
