version: '3'

services:
  metaduck:
    # This image first needs to be built from the Dockerfile in the same directory
    # It is not available from the Docker Hub
    image: metaduck
    container_name: metaduck
    ports:
      - "81:3000"
    mem_limit: 2GB
    environment:
      - MB_PLUGINS_DIR=/home/plugins
    volumes:
      - ../duckdb:/container/duckdb

networks:
  default:
    name: metadb
